// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePage(arg1) {
  return window['go']['main']['App']['CreatePage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function GetChildPages(arg1) {
  return window['go']['main']['App']['GetChildPages'](arg1);
}

export function GetPage(arg1) {
  return window['go']['main']['App']['GetPage'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdatePage(arg1) {
  return window['go']['main']['App']['UpdatePage'](arg1);
}
