// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {main} from '../models';

export function CreatePage(arg1:data.Page):Promise<data.Page>;

export function DeletePage(arg1:string):Promise<void>;

export function GetChildPages(arg1:string):Promise<Array<data.Page>>;

export function GetPage(arg1:string):Promise<data.Page>;

export function Greet(arg1:main.Person):Promise<string>;

export function UpdatePage(arg1:data.Page):Promise<void>;
